version: "3.8"

services:
  mongo:
    image:  mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - shared-network
    restart: always
    volumes:
      - ./data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx-prod
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    command: /bin/sh -c "nginx -g 'daemon off;'"
    networks:
      - shared-network

  api-prod:
    container_name: nestjs_api_prod
    image: nestjs-api-prod:1.0.0
    build:
      context: backend
      target: production
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - shared-network
    ports:
      - 8000:8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "http://api-prod:8000"]
      interval: 5s
      timeout: 3s
      retries: 6

  app-prod:
    container_name: react_app_prod
    image: react-app-prod:1.0.0
    build:
      context: front-end
      target: production
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 3000:3000
    networks:
      - shared-network
    restart: unless-stopped

networks:
  shared-network:

volumes:
  mongo_data:
